
package view.reports;

import java.awt.AlphaComposite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.JLabel;
import javax.swing.JTable;
import utility.component.ImageUtil;

/**
 *
 * @author francisunoxx
 */
public class ReportCard extends javax.swing.JDialog {
private Image schoolLogo, studentPhoto;
    /**
     * Creates new form ReportCard
     */
    public ReportCard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ImageUtil imageUtil = new ImageUtil();
        schoolLogo = imageUtil.getRenderedImageForJPanel("assets/logo.jpg", jpnlLogo);
//        studentPhoto = imageUtil.getRenderedImageForJPanel("assets/usernameIcon.jpg", jpnlStudentPhoto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpnlReceiptContainer = new javax.swing.JPanel();
        jpnlHeader = new javax.swing.JPanel();
        jpnlLogo = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(
                    RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
                g2d.setComposite(AlphaComposite.getInstance(
                    AlphaComposite.SRC_OVER, 0.8f));
            g2d.drawImage(schoolLogo, 0, 0, getWidth(), getHeight(), null);
            jpnlReceiptContainer.repaint();
        }
    };
    jPanel10 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    lblName = new javax.swing.JLabel();
    jpnlContainer = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jtableGrades = new javax.swing.JTable();
    jPanel7 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tfGWA = new javax.swing.JTextField();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jmiPrintReceipt = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jpnlReceiptContainer.setBackground(new java.awt.Color(255, 255, 255));
    jpnlReceiptContainer.setPreferredSize(new java.awt.Dimension(650, 750));
    jpnlReceiptContainer.setLayout(new java.awt.GridBagLayout());

    jpnlHeader.setBackground(new java.awt.Color(255, 255, 255));
    jpnlHeader.setForeground(new java.awt.Color(51, 51, 51));
    jpnlHeader.setLayout(new java.awt.GridBagLayout());

    jpnlLogo.setBackground(new java.awt.Color(255, 255, 255));
    jpnlLogo.setMinimumSize(new java.awt.Dimension(100, 100));
    jpnlLogo.setPreferredSize(new java.awt.Dimension(120, 120));
    jpnlLogo.setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jpnlHeader.add(jpnlLogo, gridBagConstraints);

    jPanel10.setBackground(new java.awt.Color(255, 255, 255));
    jPanel10.setPreferredSize(new java.awt.Dimension(420, 18));
    jPanel10.setLayout(new java.awt.GridBagLayout());

    jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 114, 188));
    jLabel5.setText("Mother of Perpetual Help School");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel10.add(jLabel5, gridBagConstraints);

    jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(51, 51, 51));
    jLabel7.setText("Iris Street Dahlia, West Fairview Quezon City");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel10.add(jLabel7, gridBagConstraints);

    jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(51, 51, 51));
    jLabel8.setText("1118 Metro Manila, Philippines");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel10.add(jLabel8, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.5;
    jpnlHeader.add(jPanel10, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    jpnlReceiptContainer.add(jpnlHeader, gridBagConstraints);

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setLayout(new java.awt.GridBagLayout());

    lblName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
    lblName.setForeground(new java.awt.Color(0, 0, 0));
    lblName.setText("OFFICIAL RECEIPT");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.5;
    jPanel2.add(lblName, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jpnlReceiptContainer.add(jPanel2, gridBagConstraints);

    jpnlContainer.setBackground(new java.awt.Color(255, 255, 255));
    jpnlContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
    jpnlContainer.setForeground(new java.awt.Color(0, 0, 0));
    jpnlContainer.setLayout(new java.awt.BorderLayout());

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Periodic Rating"));
    jPanel5.setLayout(new java.awt.BorderLayout());

    jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 200));

    jtableGrades.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Learning Areas", "1st Grading", "2nd Grading", "3rd Grading", "4th Grading", "Final Rating"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jtableGrades.setRowHeight(30);
    jScrollPane2.setViewportView(jtableGrades);
    if (jtableGrades.getColumnModel().getColumnCount() > 0) {
        jtableGrades.getColumnModel().getColumn(0).setResizable(false);
        jtableGrades.getColumnModel().getColumn(1).setResizable(false);
        jtableGrades.getColumnModel().getColumn(2).setResizable(false);
        jtableGrades.getColumnModel().getColumn(3).setResizable(false);
        jtableGrades.getColumnModel().getColumn(4).setResizable(false);
        jtableGrades.getColumnModel().getColumn(5).setResizable(false);
    }

    jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

    jPanel7.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("General Average:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.weightx = 0.5;
    jPanel7.add(jLabel1, gridBagConstraints);

    tfGWA.setEditable(false);
    tfGWA.setPreferredSize(new java.awt.Dimension(50, 27));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    jPanel7.add(tfGWA, gridBagConstraints);

    jPanel5.add(jPanel7, java.awt.BorderLayout.SOUTH);

    jpnlContainer.add(jPanel5, java.awt.BorderLayout.NORTH);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jpnlReceiptContainer.add(jpnlContainer, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    getContentPane().add(jpnlReceiptContainer, gridBagConstraints);

    jMenu1.setText("File");

    jmiPrintReceipt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
    jmiPrintReceipt.setText("Print");
    jMenu1.add(jmiPrintReceipt);

    jMenuItem2.setText("Exit");
    jMenu1.add(jMenuItem2);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTblGrades()
    {
        return jtableGrades;
    }
    
    public JLabel lblName()
    {
        return lblName;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jmiPrintReceipt;
    private javax.swing.JPanel jpnlContainer;
    private javax.swing.JPanel jpnlHeader;
    private javax.swing.JPanel jpnlLogo;
    private javax.swing.JPanel jpnlReceiptContainer;
    private javax.swing.JTable jtableGrades;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField tfGWA;
    // End of variables declaration//GEN-END:variables
}
