package view.faculty;

import component_model_loader.FacultyJCompModelLoader;
import component_model_loader.SubjectCategoryJCompModelLoader;
import controller.faculty.EditFacultyDialogListener;
import controller.faculty.Panel_FacultyListener;
import daoimpl.FacultyDaoImpl;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.faculty.Faculty;
import model.subjectcategory.SubjectCategory;



public class Dialog_FacultyEdit extends javax.swing.JDialog {

    /**
     * Creates new form dialog_facultyedit
     */
    private Faculty faculty;
    private SubjectCategory subjectCategory;
    private FacultyDaoImpl fdi = new FacultyDaoImpl();
    private SubjectCategoryJCompModelLoader specializationLoader = new SubjectCategoryJCompModelLoader();
    private FacultyJCompModelLoader facultyLoader = new FacultyJCompModelLoader();
    
    public Dialog_FacultyEdit(java.awt.Frame parent, boolean modal, Faculty faculty, SubjectCategory subjectCategory) {
        super(parent, modal);
        this.faculty = faculty;
        this.subjectCategory = subjectCategory;
        faculty.setFacultyID(faculty.getFacultyID());
        Object[] obj = fdi.getFacultyInfoById(faculty).toArray();
        initComponents();
        
        for(Object o : obj){
            Faculty f = (Faculty) o;
            
            tf_lastname.setText(f.getLastName());
            tf_firstname.setText(f.getFirstName());
            tf_middlename.setText(f.getMiddleName());
            tf_mobile.setText(f.getContactNo());
            tf_email.setText(f.getEmail());
            
            if(f.isStatus() == false){
                combo_status.setSelectedIndex(1);
            }
        }
        
        tf_lastname.setName("last_name");
        tf_firstname.setName("first_name");
        tf_middlename.setName("middle_name");
        
        jTable1.setModel(specializationLoader.getAllSubjectCategoryInfo(jTable1));
        jTable2.setModel(facultyLoader.loadFacultySpecialization(fdi.loadFacultySpecialization(faculty, subjectCategory),"update"));
        
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(1);
        
        jTable2.getColumnModel().getColumn(0).setMinWidth(0);
        jTable2.getColumnModel().getColumn(0).setMaxWidth(1);
        
        btn_add.addActionListener(new EditFacultyDialogListener(this, faculty));
        btn_remove.addActionListener(new EditFacultyDialogListener(this, faculty));
        btn_save.addActionListener(new EditFacultyDialogListener(this, faculty));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
    }
    
    public JTextField getTfLastname(){
        return tf_lastname;
    }
    
    public JTextField getTfFirstname(){
        return tf_firstname;
    }
    
    public JTextField getTfMiddlename(){
        return tf_middlename;
    }
    
    public JTextField getTfEmail(){
        return tf_email;
    }
    
    public JTextField getTfContact(){
        return tf_mobile;
    }
    
    public JComboBox getCbStatus(){
        return combo_status;
    }
    
    public JButton getBtnAdd(){
        return btn_add;
    }
    
    public JButton getBtnRemove(){
        return btn_remove;
    }
    
    public JButton getBtnSave(){
        return btn_save;
    }
    
    public JDialog getDialog(){
        return this;
    }
    
    public JTable getTblLoadedSpecialization(){
        return jTable1;
    }
    
    public JTable getTblFacultySpecialization(){
        return jTable2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_toppanel = new javax.swing.JPanel();
        panel_facultydetails = new javax.swing.JPanel();
        lbl_lastname = new javax.swing.JLabel();
        tf_lastname = new javax.swing.JTextField();
        lbl_firstname = new javax.swing.JLabel();
        tf_firstname = new javax.swing.JTextField();
        lbl_middlename = new javax.swing.JLabel();
        tf_middlename = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        lbl_mobile = new javax.swing.JLabel();
        tf_mobile = new javax.swing.JTextField();
        lbl_status = new javax.swing.JLabel();
        combo_status = new javax.swing.JComboBox<>();
        panel_loadspecialization = new javax.swing.JPanel();
        panel_specializationlist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_centercontrol = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        panel_currentspecialization = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panel_footer = new javax.swing.JPanel();
        btn_cancel = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Faculty");
        setMinimumSize(new java.awt.Dimension(555, 600));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel_toppanel.setMinimumSize(new java.awt.Dimension(550, 600));
        panel_toppanel.setPreferredSize(new java.awt.Dimension(550, 600));
        panel_toppanel.setLayout(new java.awt.GridBagLayout());

        panel_facultydetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Faculty Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_facultydetails.setMinimumSize(new java.awt.Dimension(550, 140));
        panel_facultydetails.setPreferredSize(new java.awt.Dimension(550, 140));
        panel_facultydetails.setLayout(new java.awt.GridBagLayout());

        lbl_lastname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_lastname.setText("Last Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel_facultydetails.add(lbl_lastname, gridBagConstraints);

        tf_lastname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_lastname.setMinimumSize(new java.awt.Dimension(150, 25));
        tf_lastname.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        panel_facultydetails.add(tf_lastname, gridBagConstraints);

        lbl_firstname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_firstname.setText("First Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel_facultydetails.add(lbl_firstname, gridBagConstraints);

        tf_firstname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_firstname.setMinimumSize(new java.awt.Dimension(150, 25));
        tf_firstname.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        panel_facultydetails.add(tf_firstname, gridBagConstraints);

        lbl_middlename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_middlename.setText("Middle Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel_facultydetails.add(lbl_middlename, gridBagConstraints);

        tf_middlename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_middlename.setMinimumSize(new java.awt.Dimension(150, 25));
        tf_middlename.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        panel_facultydetails.add(tf_middlename, gridBagConstraints);

        lbl_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_email.setText("Email Address :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        panel_facultydetails.add(lbl_email, gridBagConstraints);

        tf_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_email.setMinimumSize(new java.awt.Dimension(150, 25));
        tf_email.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 10);
        panel_facultydetails.add(tf_email, gridBagConstraints);

        lbl_mobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_mobile.setText("Mobile :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel_facultydetails.add(lbl_mobile, gridBagConstraints);

        tf_mobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_mobile.setMinimumSize(new java.awt.Dimension(150, 25));
        tf_mobile.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        panel_facultydetails.add(tf_mobile, gridBagConstraints);

        lbl_status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_status.setText("Active :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel_facultydetails.add(lbl_status, gridBagConstraints);

        combo_status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        combo_status.setMinimumSize(new java.awt.Dimension(60, 25));
        combo_status.setPreferredSize(new java.awt.Dimension(60, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        panel_facultydetails.add(combo_status, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 3);
        panel_toppanel.add(panel_facultydetails, gridBagConstraints);

        panel_loadspecialization.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Load Specialization", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_loadspecialization.setMinimumSize(new java.awt.Dimension(550, 380));
        panel_loadspecialization.setPreferredSize(new java.awt.Dimension(550, 380));
        panel_loadspecialization.setLayout(new java.awt.GridBagLayout());

        panel_specializationlist.setBorder(javax.swing.BorderFactory.createTitledBorder("Subject Category List"));
        panel_specializationlist.setMinimumSize(new java.awt.Dimension(245, 350));
        panel_specializationlist.setPreferredSize(new java.awt.Dimension(245, 350));
        panel_specializationlist.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setMinimumSize(new java.awt.Dimension(235, 330));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(235, 330));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Specialization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_specializationlist.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        panel_loadspecialization.add(panel_specializationlist, gridBagConstraints);

        panel_centercontrol.setMinimumSize(new java.awt.Dimension(40, 300));
        panel_centercontrol.setPreferredSize(new java.awt.Dimension(40, 300));
        panel_centercontrol.setLayout(new java.awt.GridBagLayout());

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_add.setText(">");
        btn_add.setMaximumSize(new java.awt.Dimension(38, 40));
        btn_add.setMinimumSize(new java.awt.Dimension(38, 40));
        btn_add.setPreferredSize(new java.awt.Dimension(38, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_centercontrol.add(btn_add, gridBagConstraints);

        btn_remove.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_remove.setText("<");
        btn_remove.setMaximumSize(new java.awt.Dimension(38, 40));
        btn_remove.setMinimumSize(new java.awt.Dimension(38, 40));
        btn_remove.setPreferredSize(new java.awt.Dimension(38, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panel_centercontrol.add(btn_remove, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panel_loadspecialization.add(panel_centercontrol, gridBagConstraints);

        panel_currentspecialization.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Specializations"));
        panel_currentspecialization.setMinimumSize(new java.awt.Dimension(245, 350));
        panel_currentspecialization.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.setMinimumSize(new java.awt.Dimension(235, 330));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(235, 330));

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Specialization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(20);
        jScrollPane2.setViewportView(jTable2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_currentspecialization.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 3, 0);
        panel_loadspecialization.add(panel_currentspecialization, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 0.5;
        panel_toppanel.add(panel_loadspecialization, gridBagConstraints);

        panel_footer.setMinimumSize(new java.awt.Dimension(550, 50));
        panel_footer.setPreferredSize(new java.awt.Dimension(550, 50));
        panel_footer.setLayout(new java.awt.GridBagLayout());

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.setMaximumSize(new java.awt.Dimension(69, 40));
        btn_cancel.setMinimumSize(new java.awt.Dimension(69, 40));
        btn_cancel.setPreferredSize(new java.awt.Dimension(69, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        panel_footer.add(btn_cancel, gridBagConstraints);

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_save.setText("Save");
        btn_save.setMaximumSize(new java.awt.Dimension(59, 40));
        btn_save.setMinimumSize(new java.awt.Dimension(59, 40));
        btn_save.setPreferredSize(new java.awt.Dimension(59, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        panel_footer.add(btn_save, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        panel_toppanel.add(panel_footer, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(panel_toppanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> combo_status;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_lastname;
    private javax.swing.JLabel lbl_middlename;
    private javax.swing.JLabel lbl_mobile;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JPanel panel_centercontrol;
    private javax.swing.JPanel panel_currentspecialization;
    private javax.swing.JPanel panel_facultydetails;
    private javax.swing.JPanel panel_footer;
    private javax.swing.JPanel panel_loadspecialization;
    private javax.swing.JPanel panel_specializationlist;
    private javax.swing.JPanel panel_toppanel;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_firstname;
    private javax.swing.JTextField tf_lastname;
    private javax.swing.JTextField tf_middlename;
    private javax.swing.JTextField tf_mobile;
    // End of variables declaration//GEN-END:variables
}
