/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moph_ui;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class DialogSectionAssignment extends javax.swing.JDialog {

    /**
     * Creates new form dialog_sectionassignment
     */
    public DialogSectionAssignment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_toopanel = new javax.swing.JPanel();
        panel_details = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        combo_gradelevel = new javax.swing.JComboBox<>();
        lbl_name1 = new javax.swing.JLabel();
        combo_gradelevel1 = new javax.swing.JComboBox<>();
        lbl_name3 = new javax.swing.JLabel();
        combo_gradelevel2 = new javax.swing.JComboBox<>();
        lbl_name4 = new javax.swing.JLabel();
        lbl_name5 = new javax.swing.JLabel();
        combo_gradelevel3 = new javax.swing.JComboBox<>();
        lbl_name6 = new javax.swing.JLabel();
        checkbox_enablemode = new javax.swing.JCheckBox();
        panel_subjectlist = new javax.swing.JPanel();
        panel_subjtable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        panel_centercontrol = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_add1 = new javax.swing.JButton();
        panel_currentsubjects = new javax.swing.JPanel();
        panel_subjtable1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        panel_footer = new javax.swing.JPanel();
        btn_cancel = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_savennew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Section Assignment");
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(900, 600));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel_toopanel.setMinimumSize(new java.awt.Dimension(900, 600));
        panel_toopanel.setPreferredSize(new java.awt.Dimension(900, 600));
        panel_toopanel.setLayout(new java.awt.GridBagLayout());

        panel_details.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_details.setMinimumSize(new java.awt.Dimension(895, 100));
        panel_details.setPreferredSize(new java.awt.Dimension(895, 100));
        panel_details.setLayout(new java.awt.GridBagLayout());

        lbl_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_name.setText("Select Grade Level :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        panel_details.add(lbl_name, gridBagConstraints);

        combo_gradelevel.setEditable(true);
        combo_gradelevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_gradelevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo_gradelevel.setMinimumSize(new java.awt.Dimension(50, 25));
        combo_gradelevel.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        panel_details.add(combo_gradelevel, gridBagConstraints);

        lbl_name1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_name1.setText("Select Section :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 0);
        panel_details.add(lbl_name1, gridBagConstraints);

        combo_gradelevel1.setEditable(true);
        combo_gradelevel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_gradelevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jupiter" }));
        combo_gradelevel1.setMinimumSize(new java.awt.Dimension(150, 25));
        combo_gradelevel1.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        panel_details.add(combo_gradelevel1, gridBagConstraints);

        lbl_name3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_name3.setText("Session :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel_details.add(lbl_name3, gridBagConstraints);

        combo_gradelevel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_gradelevel2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        combo_gradelevel2.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        panel_details.add(combo_gradelevel2, gridBagConstraints);

        lbl_name4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_name4.setText("Adviser  :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panel_details.add(lbl_name4, gridBagConstraints);

        lbl_name5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_name5.setText("Required GWA :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 5, 0);
        panel_details.add(lbl_name5, gridBagConstraints);

        combo_gradelevel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_gradelevel3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antonio, John" }));
        combo_gradelevel3.setEnabled(false);
        combo_gradelevel3.setMinimumSize(new java.awt.Dimension(150, 25));
        combo_gradelevel3.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        panel_details.add(combo_gradelevel3, gridBagConstraints);

        lbl_name6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_name6.setText("80.00");
        lbl_name6.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        panel_details.add(lbl_name6, gridBagConstraints);

        checkbox_enablemode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkbox_enablemode.setText("Enable Sectioning Mode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 5, 0);
        panel_details.add(checkbox_enablemode, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panel_toopanel.add(panel_details, gridBagConstraints);

        panel_subjectlist.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Active Students", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_subjectlist.setMinimumSize(new java.awt.Dimension(425, 400));
        panel_subjectlist.setPreferredSize(new java.awt.Dimension(425, 400));
        panel_subjectlist.setLayout(new java.awt.GridBagLayout());

        panel_subjtable.setMinimumSize(new java.awt.Dimension(405, 370));
        panel_subjtable.setPreferredSize(new java.awt.Dimension(405, 370));
        panel_subjtable.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 370));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 370));

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student Number", "Student Name", "GWA"
            }
        ));
        jTable3.setRowHeight(20);
        jScrollPane1.setViewportView(jTable3);

        panel_subjtable.add(jScrollPane1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panel_subjectlist.add(panel_subjtable, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panel_toopanel.add(panel_subjectlist, gridBagConstraints);

        panel_centercontrol.setMinimumSize(new java.awt.Dimension(40, 400));
        panel_centercontrol.setPreferredSize(new java.awt.Dimension(40, 400));
        panel_centercontrol.setLayout(new java.awt.GridBagLayout());

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_add.setText(">");
        btn_add.setMaximumSize(new java.awt.Dimension(38, 40));
        btn_add.setMinimumSize(new java.awt.Dimension(38, 40));
        btn_add.setPreferredSize(new java.awt.Dimension(38, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_centercontrol.add(btn_add, gridBagConstraints);

        btn_add1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_add1.setText("<");
        btn_add1.setMaximumSize(new java.awt.Dimension(38, 40));
        btn_add1.setMinimumSize(new java.awt.Dimension(38, 40));
        btn_add1.setPreferredSize(new java.awt.Dimension(38, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panel_centercontrol.add(btn_add1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panel_toopanel.add(panel_centercontrol, gridBagConstraints);

        panel_currentsubjects.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assigned Students", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panel_currentsubjects.setMinimumSize(new java.awt.Dimension(425, 400));
        panel_currentsubjects.setPreferredSize(new java.awt.Dimension(425, 400));
        panel_currentsubjects.setLayout(new java.awt.GridBagLayout());

        panel_subjtable1.setMinimumSize(new java.awt.Dimension(405, 370));
        panel_subjtable1.setPreferredSize(new java.awt.Dimension(405, 370));
        panel_subjtable1.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(400, 370));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 370));

        jTable4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student Number", "Student Name", "GWA"
            }
        ));
        jTable4.setRowHeight(20);
        jScrollPane2.setViewportView(jTable4);

        panel_subjtable1.add(jScrollPane2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panel_currentsubjects.add(panel_subjtable1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        panel_toopanel.add(panel_currentsubjects, gridBagConstraints);

        panel_footer.setMinimumSize(new java.awt.Dimension(798, 50));
        panel_footer.setPreferredSize(new java.awt.Dimension(798, 50));
        panel_footer.setLayout(new java.awt.GridBagLayout());

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.setMaximumSize(new java.awt.Dimension(69, 40));
        btn_cancel.setMinimumSize(new java.awt.Dimension(69, 40));
        btn_cancel.setPreferredSize(new java.awt.Dimension(69, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        panel_footer.add(btn_cancel, gridBagConstraints);

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setMaximumSize(new java.awt.Dimension(60, 40));
        btn_clear.setMinimumSize(new java.awt.Dimension(60, 40));
        btn_clear.setPreferredSize(new java.awt.Dimension(60, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panel_footer.add(btn_clear, gridBagConstraints);

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_save.setText("Save");
        btn_save.setMaximumSize(new java.awt.Dimension(59, 40));
        btn_save.setMinimumSize(new java.awt.Dimension(59, 40));
        btn_save.setPreferredSize(new java.awt.Dimension(59, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panel_footer.add(btn_save, gridBagConstraints);

        btn_savennew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_savennew.setText("Save & New");
        btn_savennew.setMaximumSize(new java.awt.Dimension(102, 40));
        btn_savennew.setMinimumSize(new java.awt.Dimension(102, 40));
        btn_savennew.setPreferredSize(new java.awt.Dimension(102, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        panel_footer.add(btn_savennew, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        panel_toopanel.add(panel_footer, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panel_toopanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogSectionAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogSectionAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogSectionAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogSectionAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogSectionAssignment dialog = new DialogSectionAssignment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_savennew;
    private javax.swing.JCheckBox checkbox_enablemode;
    private javax.swing.JComboBox<String> combo_gradelevel;
    private javax.swing.JComboBox<String> combo_gradelevel1;
    private javax.swing.JComboBox<String> combo_gradelevel2;
    private javax.swing.JComboBox<String> combo_gradelevel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_name3;
    private javax.swing.JLabel lbl_name4;
    private javax.swing.JLabel lbl_name5;
    private javax.swing.JLabel lbl_name6;
    private javax.swing.JPanel panel_centercontrol;
    private javax.swing.JPanel panel_currentsubjects;
    private javax.swing.JPanel panel_details;
    private javax.swing.JPanel panel_footer;
    private javax.swing.JPanel panel_subjectlist;
    private javax.swing.JPanel panel_subjtable;
    private javax.swing.JPanel panel_subjtable1;
    private javax.swing.JPanel panel_toopanel;
    // End of variables declaration//GEN-END:variables
}
