/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.grades;

import component_model_loader.GradeML;
import daoimpl.GradeDaoImpl;
import daoimpl.GradeLevelDaoImpl;
import daoimpl.SchoolYearDaoImpl;
import javax.swing.JOptionPane;
import model.grade.Grade;
import model.gradelevel.GradeLevel;
import model.schoolyear.SchoolYear;
import model.student.Student;
import model.subject.Subject;

/**
 *
 * @author francisunoxx
 */
public class SummerClass extends javax.swing.JPanel {
    GradeLevelDaoImpl gldi = new GradeLevelDaoImpl();
    SchoolYearDaoImpl sydi = new SchoolYearDaoImpl();
    GradeDaoImpl gdi = new GradeDaoImpl();
    
    Grade grade = new Grade();
    Subject subject = new Subject();
    GradeLevel gradeLevel = new GradeLevel();
    SchoolYear schoolYear = new SchoolYear();
    Student student = new Student();
    
    GradeML gml = new GradeML();
    public SummerClass() {
        initComponents();
        tblSummer.setModel(gml.getAllSummerStudent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSummer = new javax.swing.JTable();
        jPanel47 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel44.setBorder(null);
        jPanel44.setLayout(new java.awt.BorderLayout());

        jPanel45.setBorder(null);
        jPanel45.setPreferredSize(new java.awt.Dimension(950, 50));
        jPanel45.setLayout(new java.awt.GridBagLayout());
        jPanel44.add(jPanel45, java.awt.BorderLayout.NORTH);

        jPanel46.setBorder(null);
        jPanel46.setPreferredSize(new java.awt.Dimension(950, 454));
        jPanel46.setLayout(new java.awt.BorderLayout());

        tblSummer.setBorder(null);
        tblSummer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Number", "Student Name", "Grade Level", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSummer);
        if (tblSummer.getColumnModel().getColumnCount() > 0) {
            tblSummer.getColumnModel().getColumn(0).setResizable(false);
            tblSummer.getColumnModel().getColumn(1).setResizable(false);
            tblSummer.getColumnModel().getColumn(2).setResizable(false);
            tblSummer.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel46.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel44.add(jPanel46, java.awt.BorderLayout.CENTER);

        jPanel47.setBorder(null);
        jPanel47.setPreferredSize(new java.awt.Dimension(950, 50));
        jPanel47.setLayout(new java.awt.GridBagLayout());

        jButton5.setText("Promote All");
        jButton5.setPreferredSize(new java.awt.Dimension(130, 30));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel47.add(jButton5, gridBagConstraints);

        jPanel44.add(jPanel47, java.awt.BorderLayout.SOUTH);

        add(jPanel44, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        for(int i = 0; i < tblSummer.getRowCount(); i++)
        {
            //Setter call from SchoolYear
            schoolYear.setSchoolYearId(sydi.getCurrentSchoolYearId());
            
            student.setStudentId((int) tblSummer.getValueAt(i, 0));
                
            gradeLevel.setLevel((Integer) tblSummer.getValueAt(i, 2));
            gradeLevel.setId(gldi.getId(gradeLevel));
            
            grade.setIsPassed(true);
            
            //Method call
            if(gdi.promoteStudentById(grade, gradeLevel, student, schoolYear) == true)
            {
                JOptionPane.showMessageDialog(null, "Successful!");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSummer;
    // End of variables declaration//GEN-END:variables
}
